### ISSUE TITLE
Add support to configure base/content paths

### ISSUE THREAD

**Issue by themitvp** [nodes-vapor/admin-panel#116]
Hi, 

For the vapor 3 AdminPanel I wanted to disable the Sidebar in the admin panel for some user roles, but currently I would need to change the base/content leafs and all leafs that are pointing at the base leaf, so it could be nice to have way of configuring the base/content path at init. 

I don't have time to do it myself right now, so I am submitting this issue so I can have a look later or so somebody else can help me add this feature 😊

**Comment by rasmusebbesen** [comment]
Issue is no longer relevant as such solutions have already been implemented across several projects. Using the configurable parameter `sidebarMenuPathGenerator` we can customize the logic that generates references to different nav-templates based on user roles
