### ISSUE TITLE
Screenshots of UI

### ISSUE THREAD

**Issue by dekhaus** [nodes-vapor/admin-panel#119]
Hi

Any chance someone can post some screenshots of the UI ?  I'm curious what the UI looks like.

Thanks
Dave

**Comment by steffendsommer** [comment]
@dekhaus Sorry for the late reply and thanks for reaching out. Yes, I think this is a great idea. We'll make sure to add this with the new updated readme.

**Comment by rasmusebbesen** [comment]
Fixed in #133
