### ISSUE TITLE
Extensibility

### ISSUE THREAD

**Issue by dekhaus** [nodes-vapor/admin-panel#120]
Hi

How extensible is this library ?   For example - does the library support adding custom 'actions' in addition to the normal CRUD operations ?

Thanks
Dave

**Comment by steffendsommer** [comment]
Hi @dekhaus,

Thanks for reaching out. The Vapor 3 version (https://github.com/nodes-vapor/admin-panel/tree/vapor-3) of this package is very extensible. You can think of the package as being a framework which you can use to built your own views, functionality etc. The admin user model that is used for auth is also flexible and can be swapped out with your own if needed.

Please note that the Vapor 3 package is not fully done and tagged yet.

**Comment by steffendsommer** [comment]
Feel free to re-open if you feel this is not fully answered.
