### ISSUE TITLE
Installation instructions vapor-3

### ISSUE THREAD

**Issue by Herbse** [nodes-vapor/admin-panel#145]
Hey all,

can someone please help me to use this package? So I try to implement it in my web app, but I fail registering it in my configure.swift file. 

I tried the following way:

`try services.register(AdminPanelProvider())`

but get an "Generic parameter 'U' could not be inferred" error. Do I need to add parameters in the registering line?

Thanks a lot in advance!

**Comment by siemensikkema** [comment]
@Herbse Sorry for the long wait, you've probably moved on by now but the answer is that you need to supply the user type like so:

```swift
try services.register(AdminPanelProvider<MyAdminPanelUser>())
```
