### ISSUE TITLE
Any plans to upgrade to Vapor 4?

### ISSUE THREAD

**Issue by MrMage** [nodes-vapor/admin-panel#146]
I am currently using this package (and a few other Nodes packages) with my Vapor 3 app. However, I am now considering upgrading to Vapor 4.

Therefore, I was wondering whether you guys have any plans to update this package for compatibility with Vapor 4?

**Comment by siemensikkema** [comment]
@MrMage we have no immediate plans for that at the moment. If we do end up needing it, it will probably be a complete rewrite though.

**Comment by MrMage** [comment]
@siemensikkema thanks for the info! Are you still on Vapor 3, or have you stopped using Vapor altogether? If you are still using Vapor 3, are you maintaining a fork of it or just using the last v3 versions of the corresponding pages from the official repositories?

**Comment by siemensikkema** [comment]
@MrMage we are using Vapor 4 for all new projects (and converted some). We keep vapor3 versions of our packages around in a `vapor3` branch and the `master`/`main` branch is for Vapor 4 for the packages we still need. The reason we haven't upgraded this package yet is that we've gone mostly "headless", so API only, for our frontends. The few (2?) cases we did build a server side rendered admin panel we've done so inside the project based on Vapor 4's own building blocks together with our Submissions and Keychain packages. We didn't get around to extracting that into its own package yet.

By the way, for those projects we haven't used Leaf but https://github.com/NSHipster/HypertextLiteral instead. I might consider https://github.com/vapor-community/HTMLKit if we need another project like that as well.

**Comment by MrMage** [comment]
@siemensikkema thank you for the additional information! To be honest, I am also considering migrating my admin panel to Laravel when/if I migrate the rest of my service to Vapor 4.
