### ISSUE TITLE
Leaf Tags for common Form elements

### ISSUE THREAD

**Issue by dennishn** [nodes-vapor/admin-panel#27]
https://laravelcollective.com/docs/5.3/html

## Required:
- [x] - Form Open / Close
_Missing: Form open should be able to print out CRSF tokens_
---
- [X] - Text Input
- [ ] - Textarea Input
- [X] - Email Input
- [X] - Password Input
---
- [x] - Number Input
_Missing: Proper parsing of input value_
- [ ] - Range Input
---
- [x] - Checkbox
- [ ] - Radio Button
- [ ] - Radio Buttons Group
---
- [x] - Select single
- [ ] - Select multi
---
- [ ] - Nodes UI Date Input
- [ ] - Nodes UI File Input
- [ ] - Nodes UI Range Input
- [ ] - Nodes UI Color Input
---
- [ ] - All inputs must support an additional "attributes" array of key/values

## Nice-2-have:
- [ ] - Hidden Input
---
- [ ] - Buttons
_Should support types "submit", "reset" and "button"
---
- [ ] - Native Date Input
_Currently the "native" html5 date input is **not** supported in all browsers_
- [ ] - Native Color Input
---
- [ ] - Non-groups (no wrapping of form elements with labels / validation errors)
- [ ] - Labels
- [ ] - Validatin Errors (.help-blocks)

**Comment by Casperhr** [comment]
FormNumberGroup
//TODO Does this use fieldset?["value"]?.string ???

**Comment by Casperhr** [comment]
argumentToHtmlAttributes has force unwraps
