### ISSUE TITLE
Automate application name

### ISSUE THREAD

**Issue by BrettRToomey** [nodes-vapor/admin-panel#38]
It would be nice to have the application name on the dashboard be automated using Leaf and your configurations. More specifically, I'm talking about [this line here](https://github.com/nodes-vapor/admin-panel/blob/3449d800b91d97bc9fd521f12822774754e98e83/Sources/AdminPanel/Resources/Views/Layout/Partials/Top-bar/logo.leaf#L6)

**Comment by Casperhr** [comment]
https://github.com/nodes-vapor/admin-panel/pull/40
