### ISSUE TITLE
admin panel seeder not found

### ISSUE THREAD

**Issue by ahmedraad** [nodes-vapor/admin-panel#50]
hi, when try to run `vapor run admin-panel:seeder`
i got error 

`Usage: .build/debug/App <serve|prepare|version> `
`Error: Command "admin-panel:seeder" not found. `
`Error: Run failed.`

i Use MySQL provider, and its preparing tables successfully .

**Comment by Casperhr** [comment]
@at-daiho Sorry for late reply. This is most likely cause you have added the provider to the droplet

the provider will register this command

**Comment by at-daiho** [comment]
@Casperhr can you give me a screenshot, I can not add add command for admin-panel

**Comment by at-daiho** [comment]
@Casperhr and I have bug like:

Starting server on 0.0.0.0:8080
GET /admin/login
[Data File Error: unable to load file at path /Users/xxx/admin/Resources/Views/Login/login] [Identifier: Core.DataFileError.load] [Possible Causes: file doesn't exist, missing read permissions at specified path, data read is corrupted, system issue] [Suggested Fixes: ensure that file permissions are correct for specified paths] [Documentation Links: https://developer.apple.com/reference/foundation/filemanager]

**Comment by steffendsommer** [comment]
@at-daiho I updated the README with more precise setup information for Vapor 2. Please feel free to open a new issue if you continue to have problems setting it up.
